const ADD_ITEM = "ADD_ITEM";
const SUBTRACT_ITEM = "SUBTRACT_ITEM";
const DELETE_ITEM = "DELETE_ITEM";
const SET_PROD = "SET_PROD";
const SET_USER = "SET_USER";
const MERGE_BAGS = "MERGE_BAGS";
const CREATE_BAGS = "CREATE_BAGS";

export const Actions =
{
    ADD_ITEM,
    SUBTRACT_ITEM,
    DELETE_ITEM,
    SET_PROD,
    SET_USER,
    MERGE_BAGS,
    CREATE_BAGS,
}
